### PR TITLE
Fix Issue 2943, 2922, 2891, 2825

### LINKED ISSUE #2825: Missing crawer detection for 'mozilla/5.0 (compatible; seekportbot; +https://bot.seekport.com)'
# User agent(s)

```
mozilla/5.0 (compatible; seekportbot; +https://bot.seekport.com)
```

# Browscap version tested on

```
browscap.ini (6001003)
```

# Current result on http://browscap.org/ua-lookup

```
browser_name_pattern | *
parent | DefaultProperties
comment | Default Browser
browser | Default Browser
browser_type | unknown
browser_bits | 0
browser_maker | unknown
browser_modus | unknown
version | 0.0
majorver | 0
minorver | 0
platform | unknown
platform_version | unknown
platform_description | unknown
platform_bits | 0
platform_maker | unknown
alpha | false
beta | false
win16 | false
win32 | false
win64 | false
frames | false
iframes | false
tables | false
cookies | false
backgroundsounds | false
javascript | false
vbscript | false
javaapplets | false
activexcontrols | false
ismobiledevice | false
istablet | false
issyndicationreader | false
crawler | false
isfake | false
isanonymized | false
ismodified | false
cssversion | 0
aolversion | 0
device_name | unknown
device_maker | unknown
device_type | unknown
device_pointing_method | unknown
device_code_name | unknown
device_brand_name | unknown
renderingengine_name | unknown
renderingengine_version | unknown
renderingengine_description | unknown
renderingengine_maker | unknown
```

# Description / Further information
```
Should be marked as crawler | true
```

### LINKED ISSUE #2891: BingBot ua missing
# User agent(s)

```
Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/103.0.5060.134 Safari/537.36
```

# Browscap version tested on

< 6001005 > -  http://browscap.org/ua-lookup

# Current result on http://browscap.org/ua-lookup

```
browser_name_regex | /^.*$/
-- | --
browser_name_pattern | *
parent | DefaultProperties
comment | Default Browser
browser | Default Browser
browser_type | unknown
browser_bits | 0
browser_maker | unknown
browser_modus | unknown
version | 0.0
majorver | 0
minorver | 0
platform | unknown
platform_version | unknown
platform_description | unknown
platform_bits | 0
platform_maker | unknown
alpha | false
beta | false
win16 | false
win32 | false
win64 | false
frames | false
iframes | false
tables | false
cookies | false
backgroundsounds | false
javascript | false
vbscript | false
javaapplets | false
activexcontrols | false
ismobiledevice | false
istablet | false
issyndicationreader | false
crawler | false
isfake | false
isanonymized | false
ismodified | false
cssversion | 0
aolversion | 0
device_name | unknown
device_maker | unknown
device_type | unknown
device_pointing_method | unknown
device_code_name | unknown
device_brand_name | unknown
renderingengine_name | unknown
renderingengine_version | unknown
renderingengine_description | unknown
renderingengine_maker | unknown
```

# Description / Further information

the UA is missing.
according to https://explore.whatismybrowser.com/useragents/explore/software_name/bingbot/ this ua is "Very common".

thank you for your service, it's highly appreciated!

### LINKED ISSUE #2922: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 OPR/103.0.0.0
# User agent(s)

```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 OPR/103.0.0.0
```

# Browscap version tested on
php_browscap.ini (6001005) 

# Current result on http://browscap.org/ua-lookup

```
browser_name_regex | /^mozilla\/5\.0 \(.*windows nt 10\.0.*win64. x64.*\) applewebkit.* \(.*khtml.*like.*gecko.*\) chrome\/117\.0.*safari\/.*$/
browser_name_pattern | mozilla/5.0 (*windows nt 10.0*win64? x64*) applewebkit* (*khtml*like*gecko*) chrome/117.0*safari/*
parent | Chrome 117.0
comment | Chrome 117.0
browser | Chrome
browser_type | Browser
browser_bits | 64
browser_maker | Google Inc
browser_modus | unknown
version | 117.0
majorver | 117
minorver | 0
platform | Win10
platform_version | 10.0
platform_description | Windows 10
platform_bits | 64
platform_maker | Microsoft Corporation
alpha | false
beta | false
win16 | false
win32 | false
win64 | true
frames | true
iframes | true
tables | true
cookies | true
backgroundsounds | false
javascript | true
vbscript | false
javaapplets | false
activexcontrols | false
ismobiledevice | false
istablet | false
issyndicationreader | false
crawler | false
isfake | false
isanonymized | false
ismodified | false
cssversion | 3
aolversion | 0
device_name | Windows Desktop
device_maker | unknown
device_type | Desktop
device_pointing_method | mouse
device_code_name | Windows Desktop
device_brand_name | unknown
renderingengine_name | Blink
renderingengine_version | unknown
renderingengine_description | a WebKit Fork by Google
renderingengine_maker | Google Inc

```

# Description / Further information

The UA for OPERA needs correcting. The correct result should be OPERA version 103.

### LINKED ISSUE #2943: Support for Imagesift Bot / GPTBot
# User agent(s)

```
Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; GPTBot/1.0; +https://openai.com/gptbot)
```
```
Mozilla/5.0 (compatible; ImagesiftBot; +imagesift.com)
```

# Browscap version tested on

6001005

# Current result on http://browscap.org/ua-lookup

|Key|Value|
|:----|:----|
|browser_name_regex|/^.*$/|
|browser_name_pattern|*|
|parent|DefaultProperties|
|comment|Default Browser|
|browser|Default Browser|
|browser_type|unknown|
|browser_bits|0|
|browser_maker|unknown|
|browser_modus|unknown|
|version|0.0|
|majorver|0|
|minorver|0|
|platform|unknown|
|platform_version|unknown|
|platform_description|unknown|
|platform_bits|0|
|platform_maker|unknown|
|alpha|false|
|beta|false|
|win16|false|
|win32|false|
|win64|false|
|frames|false|
|iframes|false|
|tables|false|
|cookies|false|
|backgroundsounds|false|
|javascript|false|
|vbscript|false|
|javaapplets|false|
|activexcontrols|false|
|ismobiledevice|false|
|istablet|false|
|issyndicationreader|false|
|crawler|false|
|isfake|false|
|isanonymized|false|
|ismodified|false|
|cssversion|0|
|aolversion|0|
|device_name|unknown|
|device_maker|unknown|
|device_type|unknown|
|device_pointing_method|unknown|
|device_code_name|unknown|
|device_brand_name|unknown|
|renderingengine_name|unknown|
|renderingengine_version|unknown|
|renderingengine_description|unknown|
|renderingengine_maker|unknown|

|Key|Value|
|:----|:----|
|browser_name_regex|/^.*$/|
|browser_name_pattern|*|
|parent|DefaultProperties|
|comment|Default Browser|
|browser|Default Browser|
|browser_type|unknown|
|browser_bits|0|
|browser_maker|unknown|
|browser_modus|unknown|
|version|0.0|
|majorver|0|
|minorver|0|
|platform|unknown|
|platform_version|unknown|
|platform_description|unknown|
|platform_bits|0|
|platform_maker|unknown|
|alpha|false|
|beta|false|
|win16|false|
|win32|false|
|win64|false|
|frames|false|
|iframes|false|
|tables|false|
|cookies|false|
|backgroundsounds|false|
|javascript|false|
|vbscript|false|
|javaapplets|false|
|activexcontrols|false|
|ismobiledevice|false|
|istablet|false|
|issyndicationreader|false|
|crawler|false|
|isfake|false|
|isanonymized|false|
|ismodified|false|
|cssversion|0|
|aolversion|0|
|device_name|unknown|
|device_maker|unknown|
|device_type|unknown|
|device_pointing_method|unknown|
|device_code_name|unknown|
|device_brand_name|unknown|
|renderingengine_name|unknown|
|renderingengine_version|unknown|
|renderingengine_description|unknown|
|renderingengine_maker|unknown|

# Description / Further information

Both are bots / crawlers and should be marked as such. (Creating to get an issue for the PR)

### PR DESCRIPTION
**Pull request by abuchmann-ga**
- Detection for GPTBot
- Detection for ImagesiftBot
- Added Seekport crawler
- support to Opera until 115
- support for Opera Mobile until 85
- Android 14 detection
- MacOS X until version 14
- Improved BingBot detection

Feel free to reach out, as this is the first contribution for this project

 * Fixes #2943 
 * Fixes #2922 
 * Fixes #2891
 * Fixes #2825

### CODE REVIEW

**Review by asgrim — APPROVED** [review]

**Comment by asgrim** [comment]
Thank you @abuchmann-ga - appreciate it!

**Comment by paulrutter** [comment]
@asgrim browscap.org is not yet updated, will this happen later?

**Comment by asgrim** [comment]
> @asgrim browscap.org is not yet updated, will this happen later?

It's automated usually within 24h, but I kicked it to update :)

**Comment by paulrutter** [comment]
Released as https://github.com/blueconic/browscap-java/releases/tag/1.4.3

**Pull request merged**
