### PR TITLE
add new properties

### PR DESCRIPTION
**Pull request by mimmi20**
To be able to solve detection issues found by the parser comparasation ThaDafinser/UserAgentParserComparison I like to add these 3 fields.

### CODE REVIEW

**Comment by ThaDafinser** [comment]
:+1:

**Comment by asgrim** [comment]
@mimmi20 what about populating the existing data? separate PR?

**Comment by mimmi20** [comment]
@asgrim to change the data I will create a new PR

**Comment by asgrim** [comment]
LGTM then :) thanks

**Pull request merged**
