### PR TITLE
Add Safari 15.1

### PR DESCRIPTION
**Pull request by paulrutter**
- Add Safari 15.1 for mobile and desktop browsers
- Extend unit test

### CODE REVIEW

**Review by mimmi20 — APPROVED** [review]

**Comment by asgrim** [comment]
Thanks @paulrutter !

**Comment by paulrutter** [comment]
@asgrim can you release it on browscap.org?

**Comment by asgrim** [comment]
> @asgrim can you release it on browscap.org?

Yes, it will do, just waiting for Dependabot to pick up the change 👍

**Comment by willyaranda** [comment]
oh wow, you were super fast! thanks!

but I was collecting other UA that were failing in Apple platforms with Safari. Will open a PR later today with changes to detect them.

**Comment by paulrutter** [comment]
Cool, thanks @willyaranda !

**Pull request merged**
