### PR TITLE
Add recent Chrome, Firefox and Edge versions up until 107

### PR DESCRIPTION
**Pull request by paulrutter**
This PR adds Chrome(based) and Firefox browsers versions up until 107.
After 107 it's not clear how the user agent strings will be reduced though, although it seems the major versions will remain to be present in the UA.

I will add unit tests for some UA's later.

### CODE REVIEW

**Review by mimmi20 — APPROVED** [review]

**Review by mimmi20 — APPROVED** [review]

**Comment by paulrutter** [comment]
Sorry @mimmi20, adding a few unit tests now.
I see `Continuous Integration / Static Code Analysis with PHPStan (ubuntu-20.04, 8.1, locked) (pull_request) Failing after 40s — Static Code Analysis with PHPStan (ubuntu-20.04, 8.1, locked)` is failing, but that is not caused by my changes.

**Comment by mimmi20** [comment]
> Sorry @mimmi20, adding a few unit tests now. I see `Continuous Integration / Static Code Analysis with PHPStan (ubuntu-20.04, 8.1, locked) (pull_request) Failing after 40s — Static Code Analysis with PHPStan (ubuntu-20.04, 8.1, locked)` is failing, but that is not caused by my changes.

This is not an issue.

**Comment by paulrutter** [comment]
@mimmi20 when merged, do you have an idea when the next release will be out?
I'm planning to get this in our next platform version, so we're on time when new versions are showing up in the wild :)

**Review by asgrim — APPROVED** [review]

**Comment by asgrim** [comment]
@paulrutter Won't be long, gotta make an update on the `browscap-site` to use a newer PHP version, but that should be a quick change (famous last words.....)

**Comment by paulrutter** [comment]
Released new browscap-java version that contains the 6001000 release :)
https://github.com/blueconic/browscap-java

**Comment by asgrim** [comment]
Thanks @paulrutter !

**Pull request merged**
