### PR TITLE
Tests for lite/standard

### PR DESCRIPTION
**Pull request by mimmi20**
I have changed the Build generator for the tests and added tests for the lite and standard mode. This should solve Issue #615.

All tests who fail with the lite browscap.ini are skipped out now. I also added test groups to make it possible to test the source code for itself (call `phpunit --group sourcetest`).

PR browscap/browscap-php#84 need to be merged to get the tests running successfull.

### CODE REVIEW

**Comment by mimmi20** [comment]
@asgrim This PR will interfere with the changes you made in the branch `feature-543-reduce-lite-size`.

**Comment by asgrim** [comment]
I'd suggest increasing scrutinizer timeout to 1200:

```
inherit: true

tools:
    external_code_coverage:
        enabled: true
        timeout: 1200
        runs: 1
```

That will stop Scrutinizer timing out :)

**Comment by asgrim** [comment]
I see you've updated from master - is this ready now, @mimmi20 please?

**Comment by mimmi20** [comment]
@asgrim This is ready.

**Comment by mimmi20** [comment]
@asgrim I think there is still an error in it, but I have to search it. It was too easy to fix it.

**Comment by asgrim** [comment]
@mimmi20 dependent PR browscap/browscap-php#84 is now merged

**Comment by mimmi20** [comment]
@asgrim With profiling the unittests I found a bottleneck, which I fixed too. The tests should be about to 50% faster than before.

**Comment by asgrim** [comment]
Nice! thanks @mimmi20

**Pull request merged**
