### PR TITLE
Issue 672

### PR DESCRIPTION
**Pull request by mimmi20**
I added the new platform versions to Safari, and added a test. This should solve Issue #672.

### CODE REVIEW

**Comment by mimmi20** [comment]
@asgrim Could you restart the test on Scrutinizer?

**Comment by asgrim** [comment]
@mimmi20 I have enquired with Scruitinizer, there doesn't seem to be a retry button on this inspection, bear with me :)

**Comment by asgrim** [comment]
that works too ;)

**Comment by asgrim** [comment]
@mimmi20 haha, you replied from Scrutinizer
muller

(it's not you, just someone else with the same name hehe)

**Pull request merged**
