### PR TITLE
Add lite CSV file

### PR DESCRIPTION
**Pull request by frazjp65**
Add a lite_browscap.csv file for #1744.

### CODE REVIEW

**Comment by frazjp65** [comment]
I no longer need this. Sorry.

**Comment by asgrim** [comment]
@mimmi20 do we feel this is useful anyway? Do we need to add tests significantly too?

**Comment by mimmi20** [comment]
I dont know who is using the ini file. As the normal ini file is very large, it may be usefull.

**Comment by asgrim** [comment]
OK; we'll leave it for now :+1:

**Comment by jaydiablo** [comment]
@mimmi20 do you mean the CSV file?

**Comment by mimmi20** [comment]
yes, the csv file.

**Pull request closed without merging**
