### PR TITLE
Issue 758

### PR DESCRIPTION
**Pull request by prox2k**
Should fix Platform Version detection of iOS 8.2 up to 9.1

### CODE REVIEW

**Comment by asgrim** [comment]
@prox2k please add a test case to ensure the library does not regress:

For an example, please see: https://github.com/browscap/browscap/blob/master/tests/fixtures/issues/issue-746.php

**Comment by mimmi20** [comment]
@prox2k please change the order between `"iOS_C_9_0"´ and ´"iOS_C_9_1"´. Otherwise iOS 9.1 will not be detected.

**Comment by prox2k** [comment]
Added a Test but looks not working, it quits with following error. Suggestions appreciated.


1) BrowscapTest\UserAgentsTest::testUserAgentsLite with data set "issue-758A" ('Mozilla/5.0 (iPhone; CPU iPho...12H321', array('Safari', 'Browser', '32', 'Apple Inc', '0.0', '0', '0', 'iOS', '8.4', '32', 'Apple Inc', true, false, false, 'iPhone', 'Apple Inc', 'Mobile Phone', 'touchscreen', 'iPhone', 'Apple', 'WebKit', 'unknown', 'Apple Inc'), false)
Test skipped - Browser/Platform/Version not defined for Lite Mode

/home/sven/projects/browscap-pr/tests/BrowscapTest/UserAgentsTest.php:266
phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:186
phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:138

2) BrowscapTest\UserAgentsTest::testUserAgentsLite with data set "issue-758B" ('Mozilla/5.0 (iPhone; CPU iPho...00.1.4', array('Safari', 'Browser', '32', 'Apple Inc', '8.0', '8', '0', 'iOS', '8.4', '32', 'Apple Inc', true, false, false, 'iPhone', 'Apple Inc', 'Mobile Phone', 'touchscreen', 'iPhone', 'Apple', 'WebKit', 'unknown', 'Apple Inc'), false)
Test skipped - Browser/Platform/Version not defined for Lite Mode

**Comment by mimmi20** [comment]
@prox2k This is not an error. Your Tests are skipped from the lite mode tests.

If you set the last `false` in your test array to `true`, the test may fail if the browser, the platform or a version from this both are removed in the file `lite_php_browscap.ini`.

**Comment by asgrim** [comment]
Looks good, merging, thanks @prox2k

**Pull request merged**
