### PR TITLE
Issue 542

### PR DESCRIPTION
**Pull request by mimmi20**

### CODE REVIEW

**Comment by mimmi20** [comment]
Needs some more checks

**Comment by mimmi20** [comment]
@asgrim Can we replace the `Win16`, `Win32` and `Win64` properties with the `Crawler` property in standard mode? This would help to reduce the file size.

**Comment by asgrim** [comment]
Yes :) don't see a problem with that

**Comment by mimmi20** [comment]
All Issues I found are fixed now. Plaese merge PR #834 before this one.

**Pull request merged**
