### PR TITLE
Add recent and future chrome, edge and firefox versions, up until 125

### LINKED ISSUE #2827: Chrome 113 not detected with php_browscap Version=6001003
User Agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36'

browser_name_regex | /^mozilla\/5\.0 \(.*windows nt 10\.0.*win64. x64.*\).*applewebkit.*\(.*khtml.*like.*gecko.*\).*chrome\/.* safari\/.*$/
-- | --
browser_name_pattern | mozilla/5.0 (*windows nt 10.0*win64? x64*)*applewebkit*(*khtml*like*gecko*)*chrome/* safari/*
parent | Chrome Generic
comment | Chrome Generic
browser | Chrome
browser_type | Browser
browser_bits | 64
browser_maker | Google Inc
browser_modus | unknown
version | 0.0
majorver | 0
minorver | 0
platform | Win10
platform_version | 10.0
platform_description | Windows 10
platform_bits | 64
platform_maker | Microsoft Corporation
alpha | false
beta | false
win16 | false
win32 | false
win64 | true
frames | true
iframes | true
tables | true
cookies | true
backgroundsounds | false
javascript | true
vbscript | false
javaapplets | false
activexcontrols | false
ismobiledevice | false
istablet | false
issyndicationreader | false
crawler | false
isfake | false
isanonymized | false
ismodified | false
cssversion | 3
aolversion | 0
device_name | Windows Desktop
device_maker | unknown
device_type | Desktop
device_pointing_method | mouse
device_code_name | Windows Desktop
device_brand_name | unknown
renderingengine_name | Blink
renderingengine_version | unknown
renderingengine_description | a WebKit Fork by Google
renderingengine_maker | Google Inc

Checked on Windows 10 machine, php_browscap,ini Version=6001003

Chrome 113 not detected

### PR DESCRIPTION
**Pull request by paulrutter**
Fixes #2827

- Add recent and future chrome, edge and firefox versions, up until 125

### CODE REVIEW

**Comment by paulrutter** [comment]
The unit tests fail, would need to check those later.

**Review by mimmi20 — APPROVED** [review]

**Review by mimmi20 — CHANGES_REQUESTED** [review]
Please add the new versions also for the Desktop Chrome, the Headless Chrome and the Android Webview

**Comment by paulrutter** [comment]
I added the requested changes, awaiting the unit tests.
Maybe i'll add a few other useragents to the unit tests, please wait before merging.

**Review by mimmi20 — APPROVED** [review]

**Comment by paulrutter** [comment]
I added a few more user agents, i'm good with merging and releasing this one. 
@asgrim @mimmi20

**Review by asgrim — APPROVED** [review]

**Comment by asgrim** [comment]
Thank you @paulrutter !

**Comment by paulrutter** [comment]
Also released https://github.com/blueconic/browscap-java/releases/tag/1.4.1

**Pull request merged**
