### PR TITLE
Issue 900

### PR DESCRIPTION
**Pull request by mimmi20**
I added some new browsers, apps and bots and a lot of new tests. This PR is related to Issue #900. Please merge this PR after all other actual PRs.

### CODE REVIEW

**Comment by asgrim** [comment]
@mimmi20 needs rebase please

**Comment by asgrim** [comment]
@mimmi20 sorry - needs rebase again :) I think this is the last PR for 6014 though

**Comment by mimmi20** [comment]
@asgrim The rebase was successful

**Comment by asgrim** [comment]
Many thanks @mimmi20 :)

**Pull request merged**
