### PR TITLE
add Asus MeMO Pad 7

### PR DESCRIPTION
**Pull request by mimmi20**
I added Asus MeMO Pad 7. This should solve issue #1081.

### CODE REVIEW

**Comment by asgrim** [comment]
Conflicts, maybe with #1097?

**Comment by mimmi20** [comment]
@asgrim confloicts are solved

**Comment by asgrim** [comment]
Sorry, more conflicts, should've merged this first :/

**Comment by asgrim** [comment]
Conflict here, presumably because I just merged #1091, sorry :/

**Comment by mimmi20** [comment]
@asgrim conflicts are solved again

**Pull request merged**
